sudo: false
dist: trusty
language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "hhvm"
install:
  - composer install
script:
  - composer test
after_success:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar
  - ./coveralls.phar -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
